---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 10/29/2024 2:29 AM
---
require("__erm_toss__/global")

-- Update RTS world
local mapgen = data.raw["map-gen-presets"]["default"]
mapgen["erm-rts-world"]["basic_settings"]["autoplace_controls"][AUTOCONTROL_NAME] = { frequency = "very-high", size = "very-big" }

if mapgen["erm-debug"] then
    mapgen["erm-debug"]["basic_settings"]["autoplace_controls"][AUTOCONTROL_NAME] = { frequency = 5, size = 5 }
end


local nauvis = data.raw.planet.nauvis
nauvis.map_gen_settings.autoplace_controls[AUTOCONTROL_NAME] = {}

if feature_flags.space_travel then
    local fulgora = data.raw.planet.fulgora
    fulgora.map_gen_settings.autoplace_controls[AUTOCONTROL_NAME] = {}
end