---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
MOD_NAME = 'erm_toss'
FORCE_NAME = 'enemy_erm_toss'
MOD_VERSION = 102

DEBUG_MODE = false


-- Attack Types for on_script_trigger_effect
PROBE_ATTACK = 'empts-prb'
SHUTTLE_ATTACK = 'empts-sht'




