---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/22/2020 7:15 PM
---

-- Globals within the mod
MOD_NAME = 'erm_toss'
FORCE_NAME = 'enemy_erm_toss'

DEBUG_MODE = true


-- Attack Types for on_script_trigger_effect
PROBE_ATTACK = 'empts-prb'
SHUTTLE_ATTACK = 'empts-sht'
BOSS_SPAWN_ATTACK = 'empts-bs1'
UNITS_SPAWN_ATTACK = 'empts-bs2'

PROTOSS_MAP_COLOR = {r=0, g=255, b=255}

TRIGGER_BOSS_DIES = 'embss-die'


