---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/6/2024 9:30 AM
---

if game.surfaces['aiur'] then
    game.planets['aiur'].reset_map_gen_settings()
end 