---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 11/2/2024 7:01 PM
---

local simulations = require("__erm_toss__/prototypes/tips_and_tricks/simulations")

data:extend(
        {
            {
                type = "tips-and-tricks-item-category",
                name = FORCE_NAME,
                order = "n02-["..FORCE_NAME.."]"
            },
            {
                type = "tips-and-tricks-item",
                name = FORCE_NAME.."-general-info",
                tag = "[entity="..FORCE_NAME.."--zealot--1]",
                category = FORCE_NAME,
                order = "a",
                is_title = true,
                starting_status = "suggested",
                simulation = simulations.general
            },
            {
                type = "tips-and-tricks-item",
                name = FORCE_NAME.."-invis_darktemplar",
                tag = "[entity="..FORCE_NAME.."--invis_darktemplar--1]",
                category = FORCE_NAME,
                order = "b",
                starting_status = "suggested",
                simulation = simulations.invis_darktemplar,
                indent = 1,
            },
        }
)

if feature_flags.space_travel then
    data:extend(
            {
                {
                    type = "tips-and-tricks-item",
                    name = FORCE_NAME.."-teleportation",
                    tag = "[entity="..FORCE_NAME.."--fulgora-lightning]",
                    category = FORCE_NAME,
                    order = "c",
                    indent = 1,
                    starting_status = "suggested",
                    simulation = simulations.teleportation
                },
                {
                    type = "tips-and-tricks-item",
                    tag = "[planet=aiur]",
                    name = FORCE_NAME.."-planet-aiur",
                    category = FORCE_NAME,
                    order = "d",
                    indent = 1,
                    starting_status = "suggested",
                    simulation = simulations.planet_aiur
                },
            })
end