---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/26/2022 11:52 PM
---
local ERM_TOSS = require("__erm_toss__/global")

local ERMConfig = require("__enemyracemanager__/lib/global_config")
local ERMDataHelper = require("__enemyracemanager__/lib/rig/data_helper")
local AnimationDB = require("__erm_libs__/prototypes/animation_db")

local FALLING_PROJECTILE = 'falling_projectile'
local damage_multiplier = settings.startup["enemyracemanager-damage-multipliers"].value

--- Basic Attack #1
local create_psystorm_projectile = function(projectile_type)
    projectile_type = projectile_type or 'projectile'
    return     {
        type = "projectile",
        name = ERM_TOSS.MOD_NAME.."--psystorm--"..projectile_type,
        flags = { "not-on-map" },
        acceleration = 0,

        collision_box = {{-0.5,-0.5},{0.5, 0.5}},
        direction_only = true,
        force_condition = "enemy",
        hit_collision_mask =  { layers = {player = true, train = true,   [ERMDataHelper.getFlyingLayerName()] = true}},
        final_action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "protoss--psystorm-explosion",
                        trigger_created_entity = false
                    },
                    {
                        type = "create-smoke",
                        show_in_tooltip = true,
                        entity_name = ERM_TOSS.MOD_NAME.."--psystorm"
                    },
                }
            }
        },
        animation = AnimationDB.get_layered_animations("projectiles","stasis","projectile")
    }
end

--- Basic Attack #2
local create_stasis_projectile = function(projectile_type)
    projectile_type = projectile_type or 'projectile'
    return   {
        type = "projectile",
        name = ERM_TOSS.MOD_NAME.."--stasis--"..projectile_type,
        flags = { "not-on-map" },
        acceleration = 0,

        collision_box = {{-0.5,-0.5},{0.5, 0.5}},
        direction_only = true,
        force_condition = "enemy",
        hit_collision_mask =  { layers = {player = true, train = true,   [ERMDataHelper.getFlyingLayerName()] = true}},
        final_action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "protoss--stasis-explosion",
                        trigger_created_entity = false
                    },
                    {
                        type = "create-smoke",
                        show_in_tooltip = true,
                        entity_name = ERM_TOSS.MOD_NAME.."--stasis"
                    },
                }
            }
        },
        animation = AnimationDB.get_layered_animations("projectiles","stasis","projectile")
    }
end

--- Basic Attack #3
local create_lighting_strike = function(name, unit_probabilities)
    local aiur_lightning = util.table.deepcopy(data.raw['lightning']['lightning'])
    aiur_lightning.name = 'enemy_erm_toss--'..name..'-lightning--direct'
    aiur_lightning.damage = { amount = 500 * damage_multiplier, type = "electric" }
    aiur_lightning.energy = "5000MJ"

    for key, options in pairs(unit_probabilities) do
        table.insert(aiur_lightning.strike_effect.action_delivery.target_effects,
                {
                    type = "nested-result",
                    probability = options[1],
                    action = {
                        type = "direct",
                        action_delivery = {
                            type = "instant",
                            target_effects = {
                                {
                                    type = "create-entity",
                                    entity_name = key,
                                    offset_deviation = {{-8, -8}, {8, 8}},
                                    offsets = {
                                        {0, 0}
                                    },
                                    trigger_created_entity = true,
                                    find_non_colliding_position = true,
                                    non_colliding_search_radius = 8,
                                    non_colliding_search_precision = 2,
                                    repeat_count = options[2]
                                },
                                {
                                    type = "create-explosion",
                                    entity_name = "protoss--recall-80",
                                }
                            }
                        }
                    }
                }
        )
    end
    
    table.insert(aiur_lightning.strike_effect.action_delivery.target_effects, {
        type = "nested-result",
        action = {
            type = "area",
            force = "not-same",
            radius = 4,
            ignore_collision_condition = true,
            action_delivery = {
                type = "instant",
                target_effects = { 
                    {
                       type = "damage",
                       --- process 4 ticks per second
                       damage = { amount = 300 * damage_multiplier, type = "electric" },
                       apply_damage_to_trees = false
                    } 
                }
            }
        }
    })
    
    
    return  aiur_lightning
end

local create_damage_cloud = function (name, target_effects, radius, duration, cooldown)
    radius = radius or 2
    duration = duration or 120
    cooldown = cooldown or 15
    return  {
        name = ERM_TOSS.MOD_NAME.."--"..name,
        type = "smoke-with-trigger",
        flags = { "not-on-map" },
        show_when_smoke_off = true,
        particle_count = 1,
        render_layer = "explosion",

        affected_by_wind = false,
        duration = duration,
        cyclic = true,

        animation = util.empty_sprite(),
        action = {
            type = "direct",
            ignore_collision_condition = true,
            force = "not-same",
            action_delivery = {
                type = "instant",
                target_effects = {
                    type = "nested-result",
                    action = {
                        type = "area",
                        force = "not-same",
                        radius = radius,
                        ignore_collision_condition = true,
                        action_delivery = {
                            type = "instant",
                            target_effects = target_effects
                        }
                    }
                }
            }
        },
        action_cooldown = cooldown
    }
end


-- Super Attacks
local create_recall_projectile = function(projectile_type, script_attack)
    projectile_type = projectile_type or 'projectile'
    return   {
        type = "projectile",
        name = ERM_TOSS.MOD_NAME.."--recall-"..script_attack.."--"..projectile_type,
        flags = { "not-on-map" },
        acceleration = 0,

        collision_box = {{-1,-1},{1, 1}},
        direction_only = true,
        force_condition = "enemy",
        hit_collision_mask =  { layers = {player = true, train = true,   [ERMDataHelper.getFlyingLayerName()] = true}},
        final_action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "protoss--recall",
                        trigger_created_entity = false
                    },
                    {
                        type = "create-smoke",
                        show_in_tooltip = true,
                        entity_name = ERM_TOSS.MOD_NAME.."--recall-cloud"
                    },
                    {
                        type = "script",
                        effect_id = script_attack,
                    }
                }
            }
        },
        animation = AnimationDB.get_layered_animations("projectiles","stasis","projectile")
    }
end

local create_boss_electric_beam = function(name, beam_data)
    beam_data = beam_data or {}
    local range = beam_data['range'] or 32
    local width = beam_data['width'] or 8
    local damage = beam_data['damage'] or 100
    local default_scale = 0.75
    local animation_scale = beam_data['animation_scale'] or default_scale
    local laser_beam_blend_mode = "additive-soft"
    local beam_non_light_flags = { "trilinear-filtering" }
    local clone_beam = util.table.deepcopy(data.raw['beam']['laser-beam'])

    clone_beam.name = ERM_TOSS.MOD_NAME..'--'..name..'-'..width..'-'..range..'--beam'
    clone_beam.width = width
    clone_beam.damage_interval = 15
    clone_beam.action_triggered_automatically = true
    clone_beam.action =
    {
        type = "line",
        range = range,
        width = width,
        force = 'not-same',
        action_delivery =
        {
            type = "instant",
            target_effects =
            {
                {
                    type = "damage",
                    damage = { amount = damage * damage_multiplier, type = "laser"}
                }
            }
        }
    }
    --- The unit spawn happens on entity hit.  
    --- It's ideal to have a spawn rate of under 5% to prevent overwhelming amount of unit.
    --- But that's depends on damage_interval.  Slow attacks can have higher spawning percentage.
    if beam_data['unit_spawns'] then
        for name, chance in pairs(beam_data['unit_spawns']) do
            table.insert(clone_beam.action.action_delivery.target_effects,
    {
                type = "create-entity",
                entity_name = name,
                probability = chance / 4, --- Divide by 4 to make percentage act as per second chance.
                offset_deviation = {{-8, -8}, {8, 8}},
                offsets = {
                    {0, 0}
                },
                trigger_created_entity = true,
                find_non_colliding_position = true,
                non_colliding_search_radius = 8,
                non_colliding_search_precision = 2,
                repeat_count = ERMConfig.batch_spawn_size
            })
        end
    end
    clone_beam['graphics_set'] =
    {
        desired_segment_length = (30.91 / default_scale) * animation_scale,
        beam =
        {
            head =
            {
                layers =
                {
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/projectiles/boss_electric_beam.png",
                        line_length = 1,
                        flags = beam_non_light_flags,
                        width = 1319,
                        height = 295,
                        frame_count = 5,
                        scale = animation_scale,
                        animation_speed = 0.5,
                        blend_mode = laser_beam_blend_mode,
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/projectiles/boss_electric_beam_head_updated.png",
                        line_length = 5,
                        flags = beam_non_light_flags,
                        width = 948,
                        height = 972,
                        frame_count = 5,
                        scale = animation_scale,
                        animation_speed = 0.5,
                        blend_mode = laser_beam_blend_mode,
                        shift = util.by_pixel(-800 * animation_scale, -42.66667 * animation_scale)
                    },
                }
            },
            tail =
            {
                layers =
                {
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/projectiles/boss_electric_beam.png",
                        line_length = 1,
                        flags = beam_non_light_flags,
                        width = 1319,
                        height = 295,
                        frame_count = 5,
                        scale = animation_scale,
                        animation_speed = 0.5,
                        blend_mode = laser_beam_blend_mode
                    },
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/projectiles/boss_electric_beam_head_updated.png",
                        line_length = 5,
                        flags = beam_non_light_flags,
                        width = 948,
                        height = 972,
                        frame_count = 5,
                        scale = animation_scale,
                        animation_speed = 0.5,
                        blend_mode = laser_beam_blend_mode,
                        shift = util.by_pixel(480 * animation_scale, -42.66667 * animation_scale)
                    },
                }
            },
            body =
            {
                layers =
                {
                    {
                        filename = "__erm_toss_hd_assets__/graphics/entity/projectiles/boss_electric_beam.png",
                        line_length = 1,
                        flags = beam_non_light_flags,
                        width = 1319,
                        height = 295,
                        frame_count = 5,
                        scale = animation_scale,
                        animation_speed = 0.5,
                        blend_mode = laser_beam_blend_mode
                    }
                }
            },
        },
        ground =
        {
            head =
            {
                filename = "__base__/graphics/entity/laser-turret/laser-ground-light-tail.png",
                draw_as_light = true,
                flags = {"light"},
                line_length = 1,
                width = 64,
                height = 256,
                repeat_count = 8,
                scale = animation_scale * 2,
                shift = util.by_pixel(-32, 0),
                animation_speed = 0.5,
                tint = {0.05, 0.05, 0.5}
            },
            tail =
            {
                filename = "__base__/graphics/entity/laser-turret/laser-ground-light-tail.png",
                draw_as_light = true,
                flags = {"light"},
                line_length = 1,
                width = 64,
                height = 256,
                repeat_count = 8,
                scale = animation_scale * 2,
                shift = util.by_pixel(32, 0),
                animation_speed = 0.5,
                tint = {0.05, 0.05, 0.5}
            },
            body =
            {
                filename = "__base__/graphics/entity/laser-turret/laser-ground-light-body.png",
                draw_as_light = true,
                flags = {"light"},
                line_length = 1,
                width = 64,
                height = 256,
                repeat_count = 8,
                scale = animation_scale * 2,
                animation_speed = 0.5,
                tint = {0.05, 0.05, 0.5}
            }
        }
    }
    return clone_beam
end



data:extend({
    create_psystorm_projectile(),
    create_psystorm_projectile('falling_projectile'),
    create_damage_cloud("psystorm", {
        type = "damage",
        --- process 4 ticks per second
        damage = { amount = 200 * damage_multiplier, type = "electric" },
        apply_damage_to_trees = true
    },  6,120),
    create_stasis_projectile(),
    create_damage_cloud("stasis", {{
                                             type = "damage",
                                             --- process 4 ticks per second
                                             damage = { amount = 100 * damage_multiplier, type = "electric" },
                                             apply_damage_to_trees = false
                                         },{
                                             type = "create-sticker",
                                             sticker = "5-075-slowdown-sticker",
                                             show_in_tooltip = true,
                                         }}, 4,120),
    create_lighting_strike('land', {
        [ERM_TOSS.MOD_NAME.."--zealot--6"] = {1, 4 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--dragoon--6"] = {1, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--darktemplar--6"] = {0.5, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--invis_darktemplar--6"] = {0.2, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--templar--6"] = {0.2, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--reaver--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--darkarchon--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--archon--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
    }),
    create_lighting_strike('air', {
        [ERM_TOSS.MOD_NAME.."--scout--6"] = {1, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--corsair--6"] = {1, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--shuttle--6"] = {0.5, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--carrier--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--arbiter--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
    }),
    create_lighting_strike('mixed', {
        [ERM_TOSS.MOD_NAME.."--zealot--6"] = {0.5, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--dragoon--6"] = {0.5, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--darktemplar--6"] = {0.3, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--invis_darktemplar--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--reaver--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--darkarchon--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--archon--6"] = {0.1, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--scout--6"] = {0.5, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--corsair--6"] = {0.5, 2 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--shuttle--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--carrier--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
        [ERM_TOSS.MOD_NAME.."--arbiter--6"] = {0.2, 1 * ERMConfig.batch_spawn_size},
    }),
    create_recall_projectile(nil, ERM_TOSS.BOSS_SPAWN_ATTACK),
    create_recall_projectile(nil, ERM_TOSS.UNITS_SPAWN_ATTACK),
    create_recall_projectile('falling_projectile', ERM_TOSS.UNITS_SPAWN_ATTACK),
    create_damage_cloud("recall-cloud", {{
        type = "damage",
        --- process 4 ticks per second
        damage = { amount = 120 * damage_multiplier, type = "electric" },
        apply_damage_to_trees = true
    }},  4,120),
    create_boss_electric_beam('ultimate', {
        range = 1800, 
        damage = 200,
        width = 16,
        animation_scale = 1,
        --- The spawn chance divided by 4 in the function. It acts as % per second when it hits things.
        unit_spawns = {
            [ERM_TOSS.MOD_NAME.."--zealot--6"] = 0.1,
            [ERM_TOSS.MOD_NAME.."--dragoon--6"] = 0.05,
            [ERM_TOSS.MOD_NAME.."--invis_darktemplar--6"] = 0.01,
            [ERM_TOSS.MOD_NAME.."--archon--6"] = 0.01,
        }
    }),
    create_boss_electric_beam('special', {
        range = 1500,
        damage = 130,
        unit_spawns = {
            [ERM_TOSS.MOD_NAME.."--zealot--6"] = 0.08,
            [ERM_TOSS.MOD_NAME.."--dragoon--6"] = 0.04,
            [ERM_TOSS.MOD_NAME.."--darktemplar--6"] = 0.01,
            [ERM_TOSS.MOD_NAME.."--archon--6"] = 0.01,
        }
    })
})
