---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 01/09/2020 6:40 PM
---
local Sprites = require('__stdlib__/stdlib/data/modules/sprites')

local ERM_WeaponRig = require('__enemyracemanager__/lib/rig/weapon')
require('util')

local ProjectileAnimation = {}

function ProjectileAnimation.create_dragoon_ball()
    return {
        type = "projectile",
        name = "dragoon-projectile",
        flags = { "not-on-map" },
        acceleration = 0.005,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "dragoon-explosion-small"
                    }
                }
            }
        },
        animation = {
            layers = {
                {
                    filename = "__erm_toss__/graphics/entity/projectiles/dragoon/dragoon-ball.png",
                    frame_count = 5,
                    width = 32,
                    height = 32,
                    scale = 1.5,
                    priority = "high",
                    draw_as_glow = true,
                },
            }
        }
    }
end

function ProjectileAnimation.create_dragoon_hit_effect()
    return {
        type = "explosion",
        name = "dragoon-explosion-small",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_toss__/graphics/entity/projectiles/dragoon/dragoon-hit-effect.png",
                priority = "extra-high",
                width = 64,
                height = 64,
                frame_count = 10,
                animation_speed = 0.5,
                draw_as_glow = true,
            }
        }
    }
end

function ProjectileAnimation.create_corsair_hit_effect()
    return {
        type = "explosion",
        name = "corsair-explosion-small",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_toss__/graphics/entity/projectiles/dragoon/dragoon-hit-effect.png",
                priority = "extra-high",
                width = 64,
                height = 64,
                frame_count = 10,
                animation_speed = 0.5,
                draw_as_glow = true,
                tint = { 1, 1, 1 }
            }
        }
    }
end

function ProjectileAnimation.create_arbiter_stasis()
    return {
        type = "projectile",
        name = "stasis-projectile",
        flags = { "not-on-map" },
        acceleration = 0.005,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "stasis-explosion-small"
                    }
                }
            }
        },
        animation = {
            layers = {
                {
                    filename = "__erm_toss__/graphics/entity/projectiles/dragoon/dragoon-ball.png",
                    frame_count = 5,
                    width = 32,
                    height = 32,
                    scale = 1.5,
                    priority = "high",
                    draw_as_glow = true,
                },
            }
        }
    }
end

function ProjectileAnimation.create_arbiter_stasis_hit_effect()
    return {
        type = "explosion",
        name = "stasis-explosion-small",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_toss__/graphics/entity/projectiles/stasis/stasis.png",
                priority = "extra-high",
                width = 128,
                height = 128,
                frame_count = 13,
                animation_speed = 0.5,
                scale = 2.5,
                draw_as_glow = true,
            }
        }
    }
end

function ProjectileAnimation.create_carrier_interceptor()
    return {
        type = "projectile",
        name = "interceptor-projectile",
        flags = { "not-on-map" },
        acceleration = 0.005,
        action = {
            type = "direct",
            action_delivery = {
                type = "instant",
                target_effects = {
                    {
                        type = "create-entity",
                        entity_name = "medium-explosion"
                    }
                }
            }
        },
        animation = {
            layers = {
                {
                    filename = "__erm_toss__/graphics/entity/units/interceptor/interceptor-run.png",
                    frame_count = 1,
                    width = 32,
                    height = 32,
                    scale = 1,
                    priority = "high",
                    direction_count = 16,
                },
            }
        }
    }
end

function ProjectileAnimation.create_scout_rocket()
    return ERM_WeaponRig.remove_damage_from_rocket(
        util.table.deepcopy(data.raw['projectile']['rocket']),
        'scout-rocket'
    )
end

function ProjectileAnimation.create_electric_cloud()
    return
    {
        type = "explosion",
        name = "electric-cloud-explosion",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_toss__/graphics/entity/projectiles/psystorm/psystorm.png",
                priority = "extra-high",
                width = 224,
                height = 224,
                frame_count = 14,
                animation_speed = 0.2,
                scale = 2,
                draw_as_glow = true
            }
        }
    }
end

function ProjectileAnimation.create_archon_hit_effect()
    return
    {
        type = "explosion",
        name = "archon-hit-explosion",
        flags = { "not-on-map" },
        animations = {
            {
                filename = "__erm_toss__/graphics/entity/projectiles/archon_attack/archon-hit-effect.png",
                priority = "extra-high",
                width = 80,
                height = 80,
                frame_count = 6,
                animation_speed = 0.5,
                scale = 1.5,
                draw_as_glow = true
            }
        }
    }
end

function ProjectileAnimation.create_air_death()
    return
    {
        type = "explosion",
        name = "protoss-small-air-death",
        flags = { "not-on-map" },
        animations = {
            filename = "__erm_toss__/graphics/entity/units/air-death/air-death.png",
            width = 220,
            height = 200,
            frame_count = 15,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 1.5,
            animation_speed = 0.5,
            draw_as_glow = true
        }
    },
    {
        type = "explosion",
        name = "protoss-large-air-death",
        flags = { "not-on-map" },
        animations = {
            filename = "__erm_toss__/graphics/entity/units/air-death/air-death.png",
            width = 220,
            height = 200,
            frame_count = 15,
            direction_count = 1,
            axially_symmetrical = false,
            scale = 2.5,
            animation_speed = 0.5,
            draw_as_glow = true
        }
    }
end

function ProjectileAnimation.create_slow_ticker()
    return
    {
        type = "sticker",
        name = "protoss-slowdown-sticker",
        flags = {},
        animation = Sprites.empty_pictures(),
        duration_in_ticks = 2 * 60,
        target_movement_modifier = 0.67,
        vehicle_speed_modifier = 0.67,
    }
end

function ProjectileAnimation.create_ground_death()
    return
        {
            type = "explosion",
            name = "protoss-zealot-death",
            flags = { "not-on-map" },
            animations = {
                filename = "__erm_toss__/graphics/entity/units/zealot/zealot-death.png",
                width = 128,
                height = 128,
                frame_count = 7,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 1,
                animation_speed = 0.2,
                draw_as_glow = true
            }
        },
        {
            type = "explosion",
            name = "protoss-templar-death",
            flags = { "not-on-map" },
            animations = {
                filename = "__erm_toss__/graphics/entity/units/templar/templar-death.png",
                width = 128,
                height = 128,
                frame_count = 6,
                direction_count = 1,
                axially_symmetrical = false,
                scale = unit_scale,
                animation_speed = 0.2,
                draw_as_glow = true
            },
        }
end


return ProjectileAnimation