---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/21/2020 4:42 PM
---



local ERM_UnitHelper = require("__enemyracemanager__/lib/rig/unit_helper")
local GlobalConfig = require("__enemyracemanager__/lib/global_config")
local ERM_DebugHelper = require("__enemyracemanager__/lib/debug_helper")
local ERM_Config = require("__enemyracemanager__/lib/global_config")
local TossSound = require("__erm_toss_hd_assets__/sound")


local AnimationDB = require("__erm_libs__/prototypes/animation_db")
local Creep = require("prototypes.creep")
local enemy_autoplace = require("__enemyracemanager__/prototypes/enemy-autoplace")
local ERM_TOSS = require("__erm_toss__/global")
local name = "boss_warpgate"

-- Hitpoints

local hitpoint = 1500
local max_hitpoint_multiplier = settings.startup["enemyracemanager-max-hitpoint-multipliers"].value


-- Handles acid and poison resistance
local base_acid_resistance = 0
local incremental_acid_resistance = 50
-- Handles physical resistance
local base_physical_resistance = 0
local incremental_physical_resistance = 60
-- Handles fire and explosive resistance
local base_fire_resistance = 10
local incremental_fire_resistance = 45
-- Handles laser and electric resistance
local base_electric_resistance = 10
local incremental_electric_resistance = 45
-- Handles cold resistance
local base_cold_resistance = 10
local incremental_cold_resistance = 40


local pollution_absorption_absolute = 200
local spawning_cooldown = {780, 480}
local spawning_radius = 10
local max_count_of_owned_units = 20
local max_friends_around_to_spawn = 15
local spawn_table = function()
    local res = {}
    --Tire 2
    res[1] = { ERM_TOSS.MOD_NAME.."--scout--6", { { 0.0, 0.1 } } }
    res[2] = { ERM_TOSS.MOD_NAME.."--corsair--6", { { 0.0, 0.1 } } }
    res[3] = { ERM_TOSS.MOD_NAME.."--probe--6", { { 0.0, 0.1 } } }
    --Tire 3
    res[4] = { ERM_TOSS.MOD_NAME.."--templar--6", { { 0.0, 0.1 } } }
    res[5] = { ERM_TOSS.MOD_NAME.."--darktemplar--6", { { 0.0, 0.1 } } }
    res[6] = { ERM_TOSS.MOD_NAME.."--archon--6", { { 0.0, 0.1 } } }
    res[7] = { ERM_TOSS.MOD_NAME.."--carrier--6", { { 0.0, 0.1 } } }
    res[8] = { ERM_TOSS.MOD_NAME.."--arbiter--6", { { 0.0, 0.1 } } }
    res[9] = { ERM_TOSS.MOD_NAME.."--reaver--6", { { 0.0, 0.1 } } }
    res[10] = { ERM_TOSS.MOD_NAME.."--darkarchon--6", { { 0.0, 0.1 } } }
    return res
end

local collision_box = { { -4, -4 }, { 4, 4 } }
local map_generator_bounding_box = { { -5, -5 }, { 5, 5 } }
local selection_box = { { -4, -4 }, { 4, 4 } }

function ErmToss.make_boss_wrapgate(level, boss_data)
    level = level or 1

    data:extend({
        {
            type = "unit-spawner",
            name = ERM_TOSS.MOD_NAME .. "--" .. name .. "--" .. level,
            localised_name = { "entity-name." .. ERM_TOSS.MOD_NAME .. "--" .. name, GlobalConfig.QUALITY_MAPPING[level] },
            icon = "__erm_toss_hd_assets__/graphics/entity/icons/buildings/advisor.png",
            icon_size = 64,
            flags = { "placeable-player", "placeable-enemy" },
            max_health = boss_data.nexus_hp[level],
            order = ERM_TOSS.MOD_NAME .. "--building--" .. name .. "--".. level,
            subgroup = "enemies",
            working_sound = TossSound.building_working_sound("nexus", 1),
            dying_sound = TossSound.building_dying_sound(1),
            resistances = {
                { type = "acid", percent = 75 },
                { type = "poison", percent = 75 },
                { type = "physical", percent = 80 },
                { type = "fire", percent = 75 },
                { type = "explosion", percent = 75 },
                { type = "laser", percent = 75 },
                { type = "electric", percent = 75 },
                { type = "cold", percent = 75 },
                { type = "radioactive", percent = 66 }
            },
            healing_per_tick = 0,
            collision_box = collision_box,
            map_generator_bounding_box = map_generator_bounding_box,
            selection_box = selection_box,
            absorptions_per_second = { pollution = { absolute = pollution_absorption_absolute, proportional = 0.01 } },
            corpse = "protoss--large-base-corpse",
            dying_explosion = "protoss--large-building-explosion",
            max_count_of_owned_units = boss_data.nexus_units_count[level],
            max_friends_around_to_spawn = boss_data.nexus_units_count[level],
            map_color = ERM_UnitHelper.format_map_color(settings.startup["enemy_erm_toss-map-color"].value),
            graphics_set = {
                animations = AnimationDB.get_layered_animations("buildings", "warpgate", "run")
            },
            result_units = spawn_table(),
            -- With zero evolution the spawn rate is 6 seconds, with max evolution it is 2.5 seconds
            spawning_cooldown = boss_data.nexus_spawn_timer[level],
            spawning_radius = spawning_radius,
            spawning_spacing = 3,
            max_spawn_shift = 0,
            max_richness_for_spawn_shift = 100,
            -- distance_factor used to be 1, but Twinsen says:
            -- "The number or spitter spwners should be roughly equal to the number of biter spawners(regardless of difficulty)."
            -- (2018-12-07)
            autoplace = nil,
            call_for_help_radius = 50,
            spawn_decorations_on_expansion = true,
            spawn_decoration = Creep.getSpawnerCreep(),
            dying_trigger_effect = {
                {
                    type = "script",
                    effect_id = ERM_TOSS.TRIGGER_BOSS_DIES,
                }
            }
        }
    })
end