---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/21/2020 4:42 PM
---



local ERM_UnitHelper = require("__enemyracemanager__/lib/rig/unit_helper")
local GlobalConfig = require("__enemyracemanager__/lib/global_config")
local ERM_DebugHelper = require("__enemyracemanager__/lib/debug_helper")
local TossSound = require("__erm_toss_hd_assets__/sound")


local AnimationDB = require("__erm_libs__/prototypes/animation_db")
local Creep = require("prototypes.creep")
local enemy_autoplace = require("__enemyracemanager__/prototypes/enemy-autoplace")
local ERM_TOSS = require("__erm_toss__/global")
local name = "boss_pylon"

-- Hitpoints

local hitpoint = 600
local max_hitpoint_multiplier = settings.startup["enemyracemanager-max-hitpoint-multipliers"].value


local pollution_absorption_absolute = 100

local spawning_radius = 10

local spawn_table = function()
    local res = {}
    --Tire 1
    res[1] = { ERM_TOSS.MOD_NAME.."--zealot--6", { { 0.0, 0.7 }, {1.0, 0.1} } }
    res[2] = { ERM_TOSS.MOD_NAME.."--dragoon--6", { { 0.0, 0.3 }, {1.0, 0.1}} }
    --Tire 2
    res[3] = { ERM_TOSS.MOD_NAME.."--scout--6", { { 0.0, 0.0 }, {1.0, 0.1} } }
    res[4] = { ERM_TOSS.MOD_NAME.."--corsair--6", { { 0.0, 0.0 }, {1.0, 0.1} } }
    res[5] = { ERM_TOSS.MOD_NAME.."--probe--6", { { 0.0, 0.0 }, {1.0, 0.05} } }
    res[6] = { ERM_TOSS.MOD_NAME.."--shuttle--6", { { 0.0, 0.0 }, { 1.0, 0.05 } } }
    res[7] = { ERM_TOSS.MOD_NAME.."--darktemplar--6", { { 0.0, 0.0 },  {1.0, 0.1} } }
    --Tire 3
    res[8] = { ERM_TOSS.MOD_NAME.."--templar--6", { { 0.0, 0.0 }, {1.0, 0.05} } }
    res[9] = { ERM_TOSS.MOD_NAME.."--archon--6", { { 0.0, 0.0 },  {1.0, 0.05} } }
    res[10] = { ERM_TOSS.MOD_NAME.."--carrier--6", { { 0.0, 0.0 },  { 1.0, 0.05 } } }
    res[11] = { ERM_TOSS.MOD_NAME.."--arbiter--6", { { 0.0, 0.0 },  { 1.0, 0.05 } } }
    res[12] = { ERM_TOSS.MOD_NAME.."--reaver--6", { { 0.0, 0.0 },  { 1.0, 0.05 } } }
    res[13] = { ERM_TOSS.MOD_NAME.."--darkarchon--6", { { 0.0, 0.0 },  { 1.0, 0.05 } } }
    res[14] = { ERM_TOSS.MOD_NAME.."--invis_darktemplar--6", { { 0.0, 0.0 }, {1.0, 0.1} } }
    return res
end

local collision_box = { { -2, -2 }, { 2, 2 } }
local map_generator_bounding_box = { { -3, -3 }, { 3, 3 } }
local selection_box = { { -2, -2 }, { 2, 2 } }

function ErmToss.make_boss_pylon(level, boss_data)
    level = level or 1

    data:extend({
        {
            type = "unit-spawner",
            name = ERM_TOSS.MOD_NAME .. "--" .. name .. "--" .. level,
            localised_name = { "entity-name." .. ERM_TOSS.MOD_NAME .. "--" .. name, GlobalConfig.QUALITY_MAPPING[level] },
            icon = "__erm_toss_hd_assets__/graphics/entity/icons/buildings/advisor.png",
            icon_size = 64,
            flags = { "placeable-player", "placeable-enemy" },
            max_health = boss_data.pylon_hp[level],
            order = ERM_TOSS.MOD_NAME .. "--building--" .. name .. "--".. level,
            subgroup = "enemies",
            map_color = ERM_UnitHelper.format_map_color(settings.startup["enemy_erm_toss-map-color"].value),
            working_sound = TossSound.building_working_sound("pylon", 1),
            dying_sound = TossSound.building_dying_sound(1),
            resistances = {
                { type = "acid", percent = 50 },
                { type = "poison", percent = 50 },
                { type = "physical", percent = 66 },
                { type = "fire", percent = 50 },
                { type = "explosion", percent = 50 },
                { type = "laser", percent = 50 },
                { type = "electric", percent = 50 },
                { type = "cold", percent = 50 },
                { type = "radioactive", percent = 50 }
            },
            healing_per_tick = 0,
            collision_box = collision_box,
            map_generator_bounding_box = map_generator_bounding_box,
            selection_box = selection_box,
            absorptions_per_second = { pollution = { absolute = pollution_absorption_absolute, proportional = 0.01 } },
            corpse = "protoss--small-base-corpse",
            dying_explosion = "protoss--small-building-explosion",
            max_count_of_owned_units = boss_data.pylon_units_count[level],
            max_friends_around_to_spawn = boss_data.pylon_units_count[level],
                graphics_set = {
                animations = AnimationDB.get_layered_animations("buildings", "pylon", "run")
            },
            integration_patch = AnimationDB.get_single_animation('buildings', "pylon", 'integration_patch'),
            integration_patch_render_layer = 'ground-patch',
            result_units = spawn_table(),
            -- With zero evolution the spawn rate is 6 seconds, with max evolution it is 2.5 seconds
            spawning_cooldown = boss_data.pylon_spawn_timer[level],
            spawning_radius = spawning_radius,
            spawning_spacing = 3,
            max_spawn_shift = 0,
            max_richness_for_spawn_shift = 100,
            -- distance_factor used to be 1, but Twinsen says:
            -- "The number or spitter spwners should be roughly equal to the number of biter spawners(regardless of difficulty)."
            -- (2018-12-07)
            autoplace = nil,
            call_for_help_radius = 50,
            spawn_decorations_on_expansion = true,
            spawn_decoration = Creep.getSpawnerCreep(),
            dying_trigger_effect = {
                {
                    type = "script",
                    effect_id = ERM_TOSS.TRIGGER_BOSS_ASSIST_DIES,
                }
            },
            created_effect = {
                type = "direct",
                action_delivery = {
                    type = "instant",
                    source_effects = {
                        {
                            type = "script",
                            effect_id = ERM_TOSS.TRIGGER_BOSS_ASSIST_SPAWNED
                        }
                    }
                }
            },
        }
    })
end