---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 12/23/2020 8:27 PM
---

local CustomAttackHelper = require('__enemyracemanager__/lib/helper/custom_attack_helper')
local ERMConfig = require('__enemyracemanager__/lib/global_config')

local CustomAttacks = {}

CustomAttacks.valid = CustomAttackHelper.valid
CustomAttacks.clearTimeToLiveUnits = CustomAttackHelper.clear_time_to_live_units

function CustomAttacks.process_probe(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, CustomAttackHelper.get_unit(MOD_NAME, 'construction_buildings'))
    event.source_entity.destroy()
end

function CustomAttacks.process_shuttle(event)
    local race_settings = CustomAttackHelper.get_race_settings(MOD_NAME)
    CustomAttackHelper.drop_unit(event, MOD_NAME, 'zealot', 3)
    if CustomAttackHelper.can_spawn(80) then
        CustomAttackHelper.drop_unit(event, MOD_NAME, CustomAttackHelper.get_unit(MOD_NAME, 'droppable_units'))
    end
    if race_settings.tier == 3 and CustomAttackHelper.can_spawn(10) then
        CustomAttackHelper.drop_unit(event, MOD_NAME, 'dragoon', 2)
        CustomAttackHelper.drop_unit(event, MOD_NAME, 'reaver', 1)
    end
end

function CustomAttacks.process_carrier(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, 'interceptor', 5)
    if CustomAttackHelper.can_spawn(20) then
        CustomAttackHelper.drop_unit(event, MOD_NAME, 'interceptor', 3)
    end
end

function CustomAttacks.process_reaver(event)
    CustomAttackHelper.drop_unit(event, MOD_NAME, 'scarab', 1)
end

function CustomAttacks.process_self_destruct(event)
    event.source_entity.destroy()
end

function CustomAttacks.process_boss_units(event, batch_size)
    batch_size = batch_size or 4
    CustomAttackHelper.drop_boss_units(event, MOD_NAME, ERMConfig.boss_spawn_size * batch_size)
end

function CustomAttacks.process_batch_units(event, batch_size)
    batch_size = batch_size or 3
    CustomAttackHelper.drop_batch_units(event, MOD_NAME, ERMConfig.boss_spawn_size * batch_size)
end

return CustomAttacks